### PR TITLE
Fix lower position limit.

### LINKED ISSUE #71: Wrong initialization of the limits
The following line is not initializing properly the orientation of the base:
 https://github.com/stack-of-tasks/sot-dynamic-pinocchio/blob/e50a87ac919a4b56b1ebfd040395f498d0bac231/src/sot-dynamic-pinocchio.cpp#L269
As min means the smallest postive value, if the *real* limit is negative this is not correct.
It happens to be a problem in the release v3.5.1.

### PR DESCRIPTION
**Pull request by olivier-stasse**
The initialization was using std::numeric_limits<double>::min
instead of std::numeric_limits<double>::lowest.
Add a unit test.
Fix #71

### CODE REVIEW

File: src/sot-dynamic-pinocchio.cpp [hunk 1]
```diff
@@ -266,12 +267,13 @@ dg::Vector& DynamicPinocchio::getLowerPositionLimits(dg::Vector& res, const int&
       }
       // Found a Spherical Joint.
       // Assuming that spherical joint limits are unset
-      res(fillingIndex) = std::numeric_limits<double>::min();
-      res(fillingIndex + 1) = std::numeric_limits<double>::min();
-      res(fillingIndex + 2) = std::numeric_limits<double>::min();
+      res(fillingIndex) = std::numeric_limits<double>::lowest();
```
Comment (jmirabel) [inline src/sot-dynamic-pinocchio.cpp:270]: FYI, this is C++11 only. I don't know whether this is intentional.

Comment (jmirabel) [reply src/sot-dynamic-pinocchio.cpp:270]: If you want C++98 compatible code, use -max(). It isn't as good (see numeric_limits doc) but in this context, it is sufficient.

Comment (olivier-stasse) [reply src/sot-dynamic-pinocchio.cpp:270]: Good point thanks. I forgot to check that.
